apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-step-one
spec:
  description: >-
    This pipeline builds the environment task, provision task, and
    deprovision task using a shared workspace amongst them.
  workspaces:
    - name: ci-tools
      description: A workspace for the tools needed
  tasks:
    - name: environment-setup
      taskRef:
        name: environment
      workspaces:
        - name: ci-tools
          workspace: ci-tools
    - name: checkin-clusterclaim
      taskRef:
        name: deprovision
      runAfter:
        - environment-setup
      workspaces:
        - name: ci-tools
          workspace: ci-tools
      params: 
        - name: clusterclaim-name
          description: The name of the claimed cluster.
          value: $(tasks.<task name>.results.clusterclaim-name)
  results:    
  - name: clusterclaim-user
    description: The user cred of the claimed cluster.
    value: $(tasks.<task name>.results.clusterclaim-user)
  - name: clusterclaim-pass
    description: The pass cred of the claimed cluster.
    value: $(tasks.<task name>.results.clusterclaim-pass)
  - name: clusterclaim-api
    description: The api of the claimed cluster.
    value: $(tasks.<task name>.results.clusterclaim-api)