apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-step-one
spec:
  description: >-
    This pipeline builds the environment task, provision task, and
    deprovision task using a shared workspace amongst them.
  workspaces:
    - name: build-harness
      description: A workspace for the tools needed
  tasks:
    - name: environment
      taskRef:
        name: ci-tools
      workspaces:
        - name: build-harness
          workspace: build-harness
    - name: provision
      taskRef:
        name: provision
      runAfter:
        - environment
      workspaces:
        - name: build-harness
          workspace: build-harness
    - name: deprovision
      taskRef:
        name: deprovision
      runAfter:
        - provision
      workspaces:
        - name: build-harness
          workspace: build-harness