apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: environment-setup-pvc
spec:
  resources:
    requests:
      storage: 5M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-workspaces-run
spec:
  serviceAccountName: clusterpool-builder
  pipelineRef:
    name: build-workspaces
  workspaces:
    - name: build-harness
      persistentVolumeClaim:
        claimName: environment-setup-pvc