apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deprovision
spec:
  description: |
    Checkin cluster from clusterpool.

    This task checks in an available cluster from an existing clusterpool 
    using the build-harness. It makes this cluster available for
    multi-task manipulation via workspaces.
  workspaces: 
  - name: build-harness
    mountPath: /tekton/home/ci-tools
    description: A workspace for the tools needed
  steps:
    - name: clusterpool-claim-checkin
      env:
        - name: CLUSTER_HOST_TOKEN
          valueFrom:
            secretKeyRef:
              name: prac-secret
              key: key2
        - name: CLUSTER_HOST_API
          valueFrom:
            secretKeyRef: 
              name: prac-secret
              key: key1
      image: quay.io/emmacdon/simple-dev:latest
      script: |
        cd /tekton/home/ci-tools/build-harness
        make clusterpool/list-clusterclaims CLUSTERPOOL_HOST_TOKEN=$CLUSTER_HOST_TOKEN CLUSTERPOOL_HOST_API=$CLUSTER_HOST_API CLUSTERPOOL_LIST_ARGUMENTS=" -o json"  | jq -r '.items[] | .metadata.name' | grep "tekton" > tekton_clusterclaims.txt
        export clusterpool_to_checkin=$(head -n 1 tekton_clusterclaims.txt)
        make clusterpool/checkin CLUSTERPOOL_HOST_TOKEN=$CLUSTER_HOST_TOKEN CLUSTERPOOL_HOST_API=$CLUSTER_HOST_API CLUSTERPOOL_CLUSTER_CLAIM=$clusterpool_to_checkin