apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deprovision
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Kubernetes
    tekton.dev/tags: "aws, openshift, rhacm"
    tekton.dev/displayName: "rhacm ci"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: |
    Checkin cluster from clusterpool.

    This task checks in an available cluster from an existing clusterpool 
    using the build-harness. It makes this cluster available for
    multi-task manipulation via workspaces.
  workspaces: 
  - name: ci-tools
    mountPath: /tekton/home/ci-tools
    description: A workspace for the tools needed
  params: 
    - name: clusterclaim-name
      description: The name of the claimed cluster.
  steps:
    - name: clusterclaim-checkin
      image: quay.io/emmacdon/simple-dev:latest
      script: |
        cd $(workspaces.ci-tools.path)/build-harness
        make clusterpool/checkin CLUSTERPOOL_HOST_TOKEN=$CLUSTER_HOST_TOKEN CLUSTERPOOL_HOST_API=$CLUSTER_HOST_API CLUSTERPOOL_CLUSTER_CLAIM=$(params.clusterclaim-name)
      env:
        - name: CLUSTER_HOST_TOKEN
          valueFrom:
            secretKeyRef:
              name: prac-secret
              key: key2
        - name: CLUSTER_HOST_API
          valueFrom:
            secretKeyRef: 
              name: prac-secret
              key: key1