apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-tester-run
spec:
  serviceAccountName: clusterpool-builder
  pipelineRef:
    name: build-tester
  workspaces:
    - name: ci-tools
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5M
          volumeMode: Filesystem
          accessModes:
            - ReadWriteOnce
          storageClassName: gp2