apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-bvt
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Kubernetes
    tekton.dev/tags: ""
    tekton.dev/displayName: ""
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Build Pipeline

    This pipeline makes a basic bvt build.
  workspaces:
    - name: build-harness
      description: A workspace for build-harness
    - name: deploy-repo
      description: A workspace for deploy-repo
    - name: canary-repo
      description: A workspace for canary-repo
    - name: canary-reporting
      description: A workspace for canary-reporting
    - name: tmp-credentials
      description: A temporary workspace for kubeconfigs until a better solution is made
  params:
    - name: HOST_CLUSTER_CLAIM
      type: string
      description: Name A of the cluster to be claimed
      default: tekton-host
    - name: MANAGED_CLUSTER_CLAIM
      type: string
      description: Name B of the cluster to be claimed
      default: tekton-managed
    - name: SNAPSHOT
      type: string
      description: Snapshot to use for deploy
      default: 2.3.5-SNAPSHOT-2021-11-22-19-25-28
  tasks:
    - name: toolkit
      taskRef:
        name: toolkit
      workspaces:
        - name: build-harness
          workspace: build-harness
        - name: deploy-repo
          workspace: deploy-repo
        - name: canary-repo
          workspace: canary-repo
        - name: canary-reporting
          workspace: canary-reporting
    - name: setup-hub-environment
      taskRef:
        name: environment
      runAfter: 
        - toolkit
      workspaces:
       - name: build-harness
         workspace: build-harness
       - name: deploy-repo
         workspace: deploy-repo
       - name: creds
         workspace: tmp-credentials
      params:
        - name: build-harness
          value: $(tasks.toolkit.results.build-harness)
        - name: deploy-repo
          value: $(tasks.toolkit.results.deploy-repo)
        - name: CLUSTERCLAIM_ROLE
          value: $(params.HOST_CLUSTER_CLAIM)
        - name: snapshot
          value: $(params.SNAPSHOT)
    - name: setup-managed-environment
      taskRef:
        name: environment
      runAfter: 
        - setup-hub-environment
      workspaces:
       - name: build-harness
         workspace: build-harness
       - name: deploy-repo
         workspace: deploy-repo
       - name: creds
         workspace: tmp-credentials
      params:
        - name: build-harness
          value: $(tasks.toolkit.results.build-harness)
        - name: deploy-repo
          value: $(tasks.toolkit.results.deploy-repo)
        - name: CLUSTERCLAIM_ROLE
          value: $(params.MANAGED_CLUSTER_CLAIM)
        - name: snapshot
          value: $(params.SNAPSHOT)
  finally: 
    - name: cleanup
      taskRef:
        name: breakdown-build
      workspaces:
        - name: build-harness
          workspace: build-harness
      params: 
        - name: build-harness
          value: $(tasks.toolkit.results.build-harness)
        - name: clusterclaim-hub-name
          value: $(tasks.setup-hub-environment.results.clusterclaim-name)
        - name: clusterclaim-managed-name
          value: $(tasks.setup-managed-environment.results.clusterclaim-name)
  results:    
    - name: build-harness
      description: Pathway to use the tool build-harness
      value: $(tasks.toolkit.results.build-harness)
    - name: deploy-repo
      description: Pathway to use the tool deploy-repo
      value: $(tasks.toolkit.results.deploy-repo)
    - name: canary-repo
      description: Pathway to use the tool canary-repo
      value: $(tasks.toolkit.results.canary-repo)
    - name: canary-reporting
      description: Pathway to use the tool canary-reporting
      value: $(tasks.toolkit.results.canary-reporting)
    - name: clusterclaim-hub-name
      description: The name cred of the claimed hub cluster.
      value: $(tasks.setup-hub-environment.results.clusterclaim-name)
    - name: clusterclaim-hub-user
      description: The user cred of the claimed hub cluster.
      value: $(tasks.setup-hub-environment.results.clusterclaim-user)
    - name: clusterclaim-hub-pass
      description: The pass cred of the claimed hub cluster.
      value: $(tasks.setup-hub-environment.results.clusterclaim-pass)
    - name: clusterclaim-hub-api
      description: The api cred of the claimed hub cluster.
      value: $(tasks.setup-hub-environment.results.clusterclaim-api)
    - name: clusterclaim-hub-kubeconfig
      description: The kubeconfig of the claimed hub cluster.
      value: $(tasks.setup-hub-environment.results.clusterclaim-kubeconfig)
    - name: clusterclaim-managed-name
      description: The name cred of the claimed managed cluster.
      value: $(tasks.setup-managed-environment.results.clusterclaim-name)
    - name: clusterclaim-managed-user
      description: The user cred of the claimed managed cluster.
      value: $(tasks.setup-managed-environment.results.clusterclaim-user)
    - name: clusterclaim-managed-pass
      description: The pass cred of the claimed managed cluster.
      value: $(tasks.setup-managed-environment.results.clusterclaim-pass)
    - name: clusterclaim-managed-api
      description: The api cred of the claimed managed cluster.
      value: $(tasks.setup-managed-environment.results.clusterclaim-api)
    - name: clusterclaim-managed-kubeconfig
      description: The kubeconfig of the claimed managed cluster.
      value: $(tasks.setup-managed-environment.results.clusterclaim-kubeconfig)
