apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-tester
spec:
  description: >-
    This pipeline builds the environment task, provision task, and
    deprovision task using a shared workspace amongst them.
  workspaces:
    - name: ci-tools
      description: A workspace for the tools needed
  tasks:
    - name: environment-creation
      taskRef:
        name: environment
      workspaces:
        - name: ci-tools
          workspace: ci-tools
    - name: check
      taskRef:
        name: tester
      runAfter:
        - environment-creation
      workspaces:
        - name: ci-tools
          workspace: ci-tools
      params: 
        - name: clusterclaim-name
          value: $(tasks.environment-creation.results.clusterclaim-name)
        - name: clusterclaim-user
          value: $(tasks.environment-creation.results.clusterclaim-user)
        - name: clusterclaim-pass
          value: $(tasks.environment-creation.results.clusterclaim-pass)
        - name: clusterclaim-api
          value: $(tasks.environment-creation.results.clusterclaim-api)
    - name: checkin-clusterclaim
      taskRef:
        name: deprovision
      runAfter:
        - check
      workspaces:
        - name: ci-tools
          workspace: ci-tools
      params: 
        - name: clusterclaim-name
          value: $(tasks.environment-creation.results.clusterclaim-name)
  results: 
  - name: clusterclaim-name
    description: The name cred of the claimed cluster.
    value: $(tasks.environment-creation.results.clusterclaim-name)
  - name: clusterclaim-user
    description: The user cred of the claimed cluster.
    value: $(tasks.environment-creation.results.clusterclaim-user)
  - name: clusterclaim-pass
    description: The pass cred of the claimed cluster.
    value: $(tasks.environment-creation.results.clusterclaim-pass)
  - name: clusterclaim-api
    description: The api of the claimed cluster.
    value: $(tasks.environment-creation.results.clusterclaim-api)