apiVersion: v1
kind: ServiceAccount
metadata:
  name: bvt-cluster-claim-sa
  namespace: ci
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bvt-admin
subjects:
  - kind: ServiceAccount
    name: bvt-cluster-claim-sa
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin